version: "3.8"
   
services:
  web:
    build: .
    command: npm run start:prod
    environment:
      DB_HOST: "localhost"  # Cambiar de "db" a "localhost"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "vinyls"
      USE_SSL: "false"
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: vinyls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
