version: "3.8"
   
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "localhost"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "vinyls"
      USE_SSL: "false"
