version: "3.8"
   
services:
  web:
    build: .
    command: npm run start:prod
    volumes:
      - /usr/src/app
    environment:
     PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      USE_SSL: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  networks:
    default:
  
